spring:
  application:
    name: "price-api"
  datasource:
    url: jdbc:h2:mem:price-api
    username: price-api
    password: secret
    driverClassName: org.h2.Driver
  jpa:
    defer-datasource-initialization: true
  h2:
    console:
      enabled: true

logging:
  level:
    root: DEBUG
    web: ERROR
    data: ERROR
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: DEBUG
    org.hibernate.orm.jdbc.bind: DEBUG
